#!/usr/bin/python

import argparse

import apparmor.tools

parser = argparse.ArgumentParser(description=_('Switch the given program to complain mode'))
parser.add_argument('-d', '--dir', type=str, help=_('path to profiles'))
parser.add_argument('-r', '--remove', action='store_true', help=_('remove complain mode'))
parser.add_argument('program', type=str, nargs='+', help=_('name of program'))
args = parser.parse_args()

complain = apparmor.tools.aa_tools('complain', args)
print(args)
complain.act()
